### ISSUE TITLE
Subscriptions.Search

### ISSUE THREAD

**Issue by munknex** [lionelbarrow/braintree-go#197]
Would be nice to add this function:

[https://developers.braintreepayments.com/reference/request/subscription/search/python](https://developers.braintreepayments.com/reference/request/subscription/search/python)

**Comment by leighmcculloch** [comment]
@munknex would you like to open a PR adding it? The search objects already exist because transaction search is already implemented. It just needs expanding to Subscription. Related files you could look at for more context:

https://github.com/lionelbarrow/braintree-go/blob/a246878e7d43d6b5dc38ec985ab7b6312cf4df46/search.go#L8-L42

https://github.com/lionelbarrow/braintree-go/blob/a246878e7d43d6b5dc38ec985ab7b6312cf4df46/transaction_gateway.go#L156-L167

https://github.com/lionelbarrow/braintree-go/blob/a246878e7d43d6b5dc38ec985ab7b6312cf4df46/transaction.go#L214-L220

**Comment by leighmcculloch** [comment]
Resolved in #229.
