### ISSUE TITLE
Documentation on running tests is incorrect

### ISSUE THREAD

**Issue by tengis617** [lionelbarrow/braintree-go#235]
In both the readme and testing documentation, it is mentioned that you can run tests using `go test ./...`, but since build tags are used, no tests will be actually run. I know that its not hard to figure it out, but it would be more beginner friendly to include tags in the docs.
Maybe we can also remove build tags for unit tests ? so unit tests will always run when go `test ./...` is called?

**Comment by leighmcculloch** [comment]
I agree we need to simplify running the tests. We could remove the tags and replace them with the [testing.Short()](https://golang.org/pkg/testing/) and skipping tests when the `-short` flag is passed to `go test`. That would let someone run the unit tests alone if needed.

I'm also interested in replacing the integration tests with something similar to [ruby VCR tests](https://github.com/vcr/vcr) so that we can just run all the tests normally very quickly, and then once a day the `master` branch will build actually hitting the Braintree API. If we can do this, I think this is more meaningful and we can remove any need to distinguish between unit and integration tests.

**Comment by leighmcculloch** [comment]
I've started see how feasible VCR tests are in the [add-vcr branch](https://github.com/lionelbarrow/braintree-go/compare/add-vcr). It doesn't look that hard, but needs some work to help match responses to requests where IDs are contained in the URLs.

**Comment by leighmcculloch** [comment]
@tengis617 Yup. What I'm thinking is:

- If VCR tests mean all tests can run fast most of the time, we don't need to differentiate between unit and integration tests and we can remove the build tags.
- If VCR tests don't work out, then we'll still want to differentiate, and we can do that maybe with the `-short` instead of build tags.

But, lets hold off on doing either of those until we see what the VCR tests give us.

**Comment by leighmcculloch** [comment]
I fixed up the test documentation for now in #251 so at least it's correct, I'll open a new issue for VCRs.

**Comment by leighmcculloch** [comment]
I've opened a new issue #252 for VCR fixtures.
